name: shortmyurl
description: Url Shorttener from Heroku

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  http: any
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  validators: ^3.0.0
  flutter_launcher_icons: ^0.9.2 #flutter pub run flutter_launcher_icons:main
  flutter_native_splash: ^1.3.3 #flutter pub run flutter_native_splash:create

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: #FF9933

flutter:
  uses-material-design: true

